### ISSUE TITLE
Gui version pls

### ISSUE THREAD

**Issue by martjay** [lolleko/unreal-docset#2]
Tinkered with it for over two hours and couldn't figure out the steps at all, I can't program no experience

**Comment by lolleko** [comment]
can you tell me what exactly do you need?

You can use https://kapeli.com/dash
to download and view the docset.
You can also jut view UE's documentation on docs.unrealengine.com

**Comment by martjay** [comment]
> can you tell me what exactly do you need?
> 
> You can use https://kapeli.com/dash to download and view the docset. You can also jut view UE's documentation on docs.unrealengine.com

Bro, I use windows

**Comment by lolleko** [comment]
Try [zeal](https://zealdocs.org)... You can also download the docset directly from dash's content provider (warning third party site: https://zealusercontributions.vercel.app) and open the HTML files in your browser.

**Comment by martjay** [comment]
> Try [zeal](https://zealdocs.org)... You can also download the docset directly from dash's content provider (warning third party site: https://zealusercontributions.vercel.app) and open the HTML files in your browser.

I want to download Chinese version. but they just have English version.
